In [1]:
import pandas as pd
import numpy as np

## block data

In [2]:
df = pd.read_csv('../data/csv/blockProfitFromAddrMap.csv')

In [3]:
temp_list=np.array(range(1,len(df)+1,1))
df.index=pd.Series(temp_list)
df.head(20)

,blockNum,fromAndToBalanceDifference,fromBalanceDifference,toBalanceDifference
1,12382959,507348253875562263420,507348253875562263420,0
2,12511340,369494752458026753905,369550554954819247543,-55802496792493638
3,12875115,245786178834281450786,245786178834281450786,0
4,11728002,180340508013640933115,180340508013640933115,0
5,12274452,138927392383169489326,138927392383169489326,0
6,12478775,133952457950888452101,-99755607927223212,134052213558815675313
7,12510755,124976488115547948438,282981155148044005,124693506960399904433
8,11673416,123796706981362977094,123834765694041165727,-38058712678188633
9,12511083,122803125913406354126,-1852084987248588134,124655210900654942260
10,12188626,114381531851124384649,111670264044079679444,2711267807044705205
11,12192851,112816431586213009709,112816431586213009709,0
12,12176007,111786784747742665139,105359491980721523389,6427292767021141750
13,12197078,111164719238135933514,111164719238135933514,0
14,12192987,107967445130220078465,107967445130220078465,0
15,12196593,106955310784568040800,106955310784568040800,0
16,12151691,106896417292321241884,106896417292321241884,0
17,12162712,106562953967932299276,106395709033299557618,167244934632741658
18,12200094,106557852112635636891,106557852112635636891,0
19,12180760,106505956178900534962,106505956178900534962,0
20,12276186,106480875404308080587,106480875404308080587,0

## addr data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/csv/addrBalanceDiff_sortedByDiff.csv')

/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
temp_list=np.array(range(1,len(df)+1,1))
df.index=pd.Series(temp_list)
df.head(20)

,address,balanceDifference,maxBlockNum,minBlockNum,isFrom,isTo
1,0xf6da21e95d74767009accb145b96897ac3630bad,35976373502144792512646,12949275,12094065,1,0
2,0xffffffff34afa67c9b272a70ee743a9d857dd0ea,1052008745777181272149,12357513,12356299,1,1
3,0xae7ab96520de3a18e5e111b5eaab095312d7fe84,594946829404599872835,12989984,11768729,0,1
4,0x7fcad8cc6ea5c55215e7e76872609aedfff86bc1,511046353600000000000,12382959,12361652,1,0
5,0xecbb27eb44033a24e76a56bb23129bdbef4f44e2,398721720130536696050,12987930,12981615,1,1
6,0xfd225193f80f40053fd1a1548bca6cf0e6577bb4,369410479989965095450,12941893,12271954,1,0
7,0x7d92ad7e1b6ae22c6a43283af3856028cd3d856a,308564846871307799120,12541521,11735098,1,0
8,0x12429f1842c56e2116f93cbd6cf09418e49abcd7,299873871407512895471,12981713,11566885,1,0
9,0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c,257703452497992570179,12989975,12348895,1,0
10,0x3eff38c0e1e5dd6bd58d3fa79caecc4da46c8866,246841811842510769179,12875176,12875115,1,0
11,0x5c1d2886a6fd3b7264d6afc309979760782e0f71,246792196058251865683,12357153,12351819,1,0
12,0x78cce34b82f8cef05eb658ddcf10f9a154298ed4,242041604754951791909,12735950,12258169,0,1
13,0xda1faeb056a2f568b138ca0ad9ad8a51915ba336,225582135828526022409,12736501,12212650,0,1
14,0x8c092ce2619c4694c7376f443686ddaf1f11920b,191649692449710043056,12529499,12357490,1,0
15,0xaf2a082188ad55993c0fbf1e067c01f27cc69e1d,182208922477533258434,12356599,12345015,1,0
16,0x370a4f3d25093cff96837c588229fa1f2e2ca5c6,159301933126784561449,12356511,12354839,1,0
17,0xea674fdde714fd979de3edf0f56aa9716b898ec8,149475356966930314738,12989990,11538222,1,1
18,0x829bd824b016326a401d083b33d092293333a830,145205869068194698049,12989973,12354879,1,0
19,0x7ad979c0c7b1a04a37bed2f6be738761dfb8bbc2,144020107279500000000,12978067,12276186,1,0
20,0xaa7a210aef1d9d316698371a38aed0e8bbbf0d20,138926212405129682917,12274452,12274452,1,0